export const categoryConstants = {
    GETALL_REQUEST: 'CATEGORY_GETALL_REQUEST',
    GETALL_SUCCESS: 'CATEGORY_GETALL_SUCCESS',
    GETALL_FAILURE: 'CATEGORY_GETALL_FAILURE',

    GETBYID_REQUEST: 'CTEGORY_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'CTEGORY_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'CTEGORY_GETBYID_FAILURE'
};