export const certificateConstants = {
    GETCERTIFICATE_REQUEST: 'GETCERTIFICATE_REQUEST',
    GETCERTIFICATE_SUCCESS: 'GETCERTIFICATE_SUCCESS',
    GETCERTIFICATE_FAILURE: 'GETCERTIFICATE_FAILURE'
};