export const commentConstants = {
    GETBYCOURSEID_REQUEST: 'COMMENT_GETBYCOURSEID_REQUEST',
    GETBYCOURSEID_SUCCESS: 'COMMENT_GETBYCOURSEID_SUCCESS',
    GETBYCOURSEID_FAILURE: 'COMMENT_GETBYCOURSEID_FAILURE',

    ADD_REQUEST: 'COMMENT_ADD_REQUEST',
    ADD_SUCCESS: 'COMMENT_ADD_SUCCESS',
    ADD_FAILURE: 'COMMENT_ADD_FAILURE',

    DELETE_REQUEST: 'COMMENT_DELETE_REQUEST',
    DELETE_SUCCESS: 'COMMENT_DELETE_SUCCESS',
    DELETE_FAILURE: 'COMMENT_DELETE_FAILURE',
};