export const courseConstants = {
    GETALL_REQUEST: 'COURSE_GETALL_REQUEST',
    GETALL_SUCCESS: 'COURSE_GETALL_SUCCESS',
    GETALL_FAILURE: 'COURSE_GETALL_FAILURE',

    GETPOPULAR_REQUEST: 'COURSE_GETPOPULAR_REQUEST',
    GETPOPULAR_SUCCESS: 'COURSE_GETPOPULAR_SUCCESS',
    GETPOPULAR_FAILURE: 'COURSE_GETPOPULAR_FAILURE',

    GETRECOM_REQUEST: 'COURSE_GETRECOM_REQUEST',
    GETRECOM_SUCCESS: 'COURSE_GETRECOM_SUCCESS',
    GETRECOM_FAILURE: 'COURSE_GETRECOM_FAILURE',

    GETPAGINATED_REQUEST: 'COURSE_GETPAGINATED_REQUEST',
    GETPAGINATED_SUCCESS: 'COURSE_GETPAGINATED_SUCCESS',
    GETPAGINATED_FAILURE: 'COURSE_GETPAGINATED_FAILURE',

    GETBYID_REQUEST: 'COURSE_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'COURSE_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'COURSE_GETBYID_FAILURE',

    GETBYCATEGORYID_REQUEST: 'COURSE_GETBYCATEGORYID_REQUEST',
    GETBYCATEGORYID_SUCCESS: 'COURSE_GETBYCATEGORYID_SUCCESS',
    GETBYCATEGORYID_FAILURE: 'COURSE_GETBYCATEGORYID_FAILURE',
    
    GETBYUSER_REQUEST: 'COURSE_GETBYUSER_REQUEST',
    GETBYUSER_SUCCESS: 'COURSE_GETBYUSER_SUCCESS',
    GETBYUSER_FAILURE: 'COURSE_GETBYUSER_FAILURE',

    SUBSCRIBE_REQUEST: 'COURSE_SUBSCRIBE_REQUEST',
    SUBSCRIBE_SUCCESS: 'COURSE_SUBSCRIBE_SUCCESS',
    SUBSCRIBE_FAILURE: 'COURSE_SUBSCRIBE_FAILURE',

    UNSUBSCRIBE_REQUEST: 'COURSE_UNSUBSCRIBE_REQUEST',
    UNSUBSCRIBE_SUCCESS: 'COURSE_UNSUBSCRIBE_SUCCESS',
    UNSUBSCRIBE_FAILURE: 'COURSE_UNSUBSCRIBE_FAILURE',

    SEARCH_REQUEST: 'COURSE_SEARCH_REQUEST'
};