export const lessonConstants = {
    GETBYCOURSEID_REQUEST: 'LESSON_GETBYCOURSEID_REQUEST',
    GETBYCOURSEID_SUCCESS: 'LESSON_GETBYCOURSEID_SUCCESS',
    GETBYCOURSEID_FAILURE: 'LESSON_GETBYCOURSEID_FAILURE',

    GETBYID_REQUEST: 'LESSON_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'LESSON_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'LESSON_GETBYID_FAILURE'
};