export const resultConstants = {
    ADD_REQUEST: 'ADD_REQUEST',
    ADD_SUCCESS: 'ADD_SUCCESS',
    ADD_FAILURE: 'ADD_FAILURE',

    GETHISTORY_REQUEST: 'GETHISTORY_REQUEST',
    GETHISTORY_SUCCESS: 'GETHISTORY_SUCCESS',
    GETHISTORY_FAILURE: 'GETHISTORY_FAILURE'
}