export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    EDIT_REQUEST: 'USERS_EDIT_REQUEST',
    EDIT_SUCCESS: 'USERS_EDIT_SUCCESS',
    EDIT_FAILURE: 'USERS_EDIT_FAILURE',
    
    UPDATEAVATAR_REQUEST: 'USERS_UPDATEAVATAR_REQUEST',
    UPDATEAVATAR_SUCCESS: 'USERS_UPDATEAVATAR_SUCCESS',
    UPDATEAVATAR_FAILURE: 'USERS_UPDATEAVATAR_FAILURE',

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE',

    GETPROFILE_REQUEST: 'USERS_GETPROFILE_REQUEST',
    GETPROFILE_SUCCESS: 'USERS_GETPROFILE_SUCCESS',
    GETPROFILE_FAILURE: 'USERS_GETPROFILE_FAILURE',

    GETBYID_REQUEST: 'USERS_GETBYID_REQUEST',
    GETBYID_SUCCESS: 'USERS_GETBYID_SUCCESS',
    GETBYID_FAILURE: 'USERS_GETBYID_FAILURE',

    EDITPASSWORD_REQUEST: 'USERS_EDITPASSWORD_REQUEST',
    EDITPASSWORD_SUCCESS: 'USERS_EDITPASSWORD_SUCCESS',
    EDITPASSWORD_FAILURE: 'USERS_EDITPASSWORD_FAILURE',

    LOGOUT: 'USERS_LOGOUT'
};